# Generated by Django 4.0.6 on 2023-08-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_avatar_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default.png', null=True, upload_to=''),
        ),
    ]
